{
    "errors": [
        {
            "message": "Query \"getAll\" has depth of 3, which exceeds max depth of 2",
            "locations": [
                {
                    "line": 1,
                    "column": 1
                }
            ]
        },
        {
            "message": "Query \"getPerson\" has depth of 3, which exceeds max depth of 2",
            "locations": [
                {
                    "line": 15,
                    "column": 1
                }
            ]
        }
    ]
}
